"""initial schema

Revision ID: 550ccd22c6fd
Revises: 
Create Date: 2026-02-05 16:42:20.778383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '550ccd22c6fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('beat_count', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('familiarity', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('dance_style', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('beat_count > 0', name='ck_moves_beat_count_positive'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 10', name='ck_moves_difficulty_range'),
    sa.CheckConstraint('familiarity >= 1 AND familiarity <= 10', name='ck_moves_familiarity_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moves_user_dance_style', 'moves', ['user_id', 'dance_style'], unique=False)
    op.create_index('ix_moves_user_id', 'moves', ['user_id'], unique=False)
    op.create_table('move_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_move_id', sa.UUID(), nullable=False),
    sa.Column('target_move_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_move_id != target_move_id', name='ck_no_self_connection'),
    sa.ForeignKeyConstraint(['source_move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_move_id', 'target_move_id', name='uq_connection_per_user')
    )
    op.create_table('move_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('move_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gcs_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_videos')
    op.drop_table('move_connections')
    op.drop_index('ix_moves_user_id', table_name='moves')
    op.drop_index('ix_moves_user_dance_style', table_name='moves')
    op.drop_table('moves')
    op.drop_table('users')
    # ### end Alembic commands ###
