"""add_move_cues_table

Revision ID: 9ce5f1b3e7f7
Revises: 5f2926f49d07
Create Date: 2026-03-20 15:51:56.981314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce5f1b3e7f7'
down_revision: Union[str, None] = '5f2926f49d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_cues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('move_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('beat', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=20), nullable=False),
    sa.Column('body_part', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('beat >= 1', name='ck_cue_beat_positive'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('move_id', 'beat', 'person', 'body_part', name='uq_cue_per_beat_person_part')
    )
    op.create_index('ix_move_cues_move_id', 'move_cues', ['move_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_move_cues_move_id', table_name='move_cues')
    op.drop_table('move_cues')
    # ### end Alembic commands ###
